Moves the frontend generic configuration to a new plugin
jupyter-server/jupyverse pull request #231
Opened 2022-09-19 16:44 UTC by hbcarlos

cc @davidbrochart 

This PR moves the generic frontend configuration to a new plugin.

The idea is that another fps-base app could reuse the kernel plugin without depending on the fps-lab plugin, being able to implement a new frontend that reuses the kernel plugin.

2022-09-19 17:09 UTC, hbcarlos commented
I believe the Check Release workflow is failing because of an unrelated issue. It is failing in the main branch too, and I think it is related to the order used to install the packages in the step `check-python`.

2022-09-20 07:08 UTC, davidbrochart requested changes
Thanks Carlos!
The Check Release workflow is failing because we have not published `fps-frontent` to PyPI yet, so that's expected. I'll do it after merging this PR.
@blink1073 mentioned that jupyter-releaser should support local packages though, but I don't know if there's something to do to enable that?

2022-09-20 07:08 UTC, davidbrochart commented on plugins/kernels/fps_kernels/routes.py
> +    lab_config=Depends(get_frontend_config),
```suggestion
    frontend_config=Depends(get_frontend_config),
```
And replace `lab_config` with `frontend_config` in this file.

2022-09-20 07:08 UTC, davidbrochart commented on plugins/lab/fps_lab/routes.py
> +        lab_config=Depends(get_frontend_config),
```suggestion
        frontend_config=Depends(get_frontend_config),
```

2022-09-20 07:08 UTC, davidbrochart commented on plugins/lab/fps_lab/routes.py
> +        lab_config=Depends(get_frontend_config),
```suggestion
        frontend_config=Depends(get_frontend_config),
```

2022-09-20 07:08 UTC, davidbrochart commented on pyproject.toml
> +python_packages = [ "plugins/auth:fps-auth", "plugins/auth_fief:fps-auth-fief", "plugins/contents:fps-contents", "plugins/frontend:fps-frontend", "plugins/jupyterlab:fps-jupyterlab", "plugins/kernels
```suggestion
python_packages = [ "plugins/auth:fps-auth", "plugins/auth_fief:fps-auth-fief", "plugins/contents:fps-contents", "plugins/frontend:fps-frontend", "plugins/jupyterlab:fps-jupyterlab", "plugins/kernels:fps-kernels", "plugins/lab:fps-lab", "plugins/nbconvert:fps-nbconvert", "plugins/retrolab:fps-retrolab", "plugins/terminals:fps-terminals", "plugins/yjs:fps-yjs", "plugins/login:fps-login", ".:jupyverse:fps-auth,fps-auth-fief,fps-contents,fps-jupyterlab,fps-kernels,fps-lab,fps-frontend,fps-nbconvert,fps-retrolab,fps-terminals,fps-yjs",]
```

2022-09-20 08:24 UTC, hbcarlos commented
Thanks, @davidbrochart! I pushed a commit with the changes.

2022-09-20 08:36 UTC, davidbrochart approved these changes

2022-09-20 08:52 UTC, merged

2022-09-20 13:27 UTC, blink1073 commented
> local packages

It should already be doing that in check release, using a local pypi server, but that server only serves files that you've published.