Create a base auth plugin to depend on instead of jupyverse
jupyter-server/jupyverse pull request #232
Opened 2022-09-20 17:01 UTC by hbcarlos

cc @davidbrochart

2022-09-20 20:43 UTC, davidbrochart requested changes
Thanks a lot Carlos, that looks good.

2022-09-20 20:43 UTC, davidbrochart commented on plugins/auth_base/fps_auth_base/__init__.py
> +        "For instance: pip install fps-auth",
```suggestion
        "An auth plugin must be installed, for instance: pip install fps-auth"
```

2022-09-20 20:43 UTC, davidbrochart commented on fps_cli_args.toml
> +mode = "noauth"
This file should not be committed.

2022-09-20 20:43 UTC, davidbrochart commented on plugins/auth_base/pyproject.toml
> +
```suggestion
```

2022-09-20 21:20 UTC, hbcarlos commented
Thanks, David! I added a commit with the changes.

2022-09-21 05:33 UTC, davidbrochart commented on pyproject.toml
> +python_packages = ["plugins/auth:fps-auth-base", "plugins/auth:fps-auth", "plugins/auth_fief:fps-auth-fief", "plugins/contents:fps-contents", "plugins/frontend:fps-frontend", "plugins/jupyterlab:fps-
I forgot that one.
```suggestion
python_packages = ["plugins/auth_base:fps-auth-base", "plugins/auth:fps-auth", "plugins/auth_fief:fps-auth-fief", "plugins/contents:fps-contents", "plugins/frontend:fps-frontend", "plugins/jupyterlab:fps-jupyterlab", "plugins/kernels:fps-kernels", "plugins/lab:fps-lab", "plugins/nbconvert:fps-nbconvert", "plugins/retrolab:fps-retrolab", "plugins/terminals:fps-terminals", "plugins/yjs:fps-yjs", "plugins/login:fps-login", ".:jupyverse:fps-auth-base,fps-auth,fps-auth-fief,fps-contents,fps-jupyterlab,fps-kernels,fps-lab,fps-frontend,fps-nbconvert,fps-retrolab,fps-terminals,fps-yjs",]
```

2022-09-21 05:34 UTC, davidbrochart approved these changes

2022-09-21 05:34 UTC, merged