Fix incomplete kernel search path
jupyter-server/jupyverse pull request #246
Opened 2022-11-11 09:30 UTC by Wh1isper

2022-11-14 02:25 UTC, Wh1isper commented
cc @davidbrochart

2022-11-14 04:03 UTC, Wh1isper commented
I missed the change to the kernel driver, will check the ipython kernelspec search path

2022-11-15 07:22 UTC, davidbrochart commented
Thanks for the PR @Wh1isper, any idea why tests fail?

2022-11-15 08:14 UTC, Wh1isper commented
> Thanks for the PR @Wh1isper, any idea why tests fail?

It seems like starlette switch `requests` to `httpx` and not support `get` with body

https://github.com/encode/starlette/blob/master/starlette/testclient.py#L470

2022-11-15 08:18 UTC, Wh1isper commented
refer to this
https://www.python-httpx.org/compatibility/#request-body-on-http-methods
just fixed ci

2022-11-15 16:26 UTC, davidbrochart requested changes

2022-11-15 16:26 UTC, davidbrochart commented on plugins/kernels/fps_kernels/routes.py
> +    return {"default": f"{kernel_config.default_kernel}", "kernelspecs": kernelspecs}
```suggestion
    return {"default": kernel_config.default_kernel, "kernelspecs": kernelspecs}
```

2022-11-15 16:26 UTC, davidbrochart commented on plugins/kernels/fps_kernels/routes.py
> +    raise HTTPException(404)
```suggestion
    raise HTTPException(status_code=404, detail=f"Kernelspec {kernel_name}/{file_name} not found")
```

2022-11-15 16:26 UTC, davidbrochart commented on plugins/kernels/fps_kernels/routes.py
> +        kernelspec_path=find_kernelspec(kernel_name),
```suggestion
        kernelspec_path=Path(find_kernelspec(kernel_name)).as_posix(),
```

2022-11-15 16:26 UTC, davidbrochart commented on plugins/kernels/fps_kernels/routes.py
> +                kernelspec_path=find_kernelspec(kernel["name"]),
```suggestion
                kernelspec_path=Path(find_kernelspec(kernel["name"])).as_posix(),
```

2022-11-17 14:31 UTC, davidbrochart commented
> It seems like starlette switch `requests` to `httpx` and not support `get` with body

Should we require `starlette >=0.21.0`?

2022-11-17 14:42 UTC, Wh1isper commented
> > It seems like starlette switch `requests` to `httpx` and not support `get` with body
> 
> Should we require `starlette >=0.21.0`?

`fastapi ==0.87.0` will get `starlette==0.21.0`, require `fastapi >=0.87.0` should be ok?

I'm new to `fastapi`, it looks like fastapi will follow up with `starlette` for updates

2022-11-17 14:45 UTC, davidbrochart commented
> `fastapi ==0.87.0` will get `starlette==0.21.0`, require `fastapi >=0.87.0` should be ok?

Yes, let's require `fastapi >=0.87.0` then :+1:

2022-11-17 15:19 UTC, merged

2022-11-17 15:36 UTC, davidbrochart commented
Just as a side note, you should create a branch on your fork before making a PR, instead of committing on `main`.

2022-11-18 00:05 UTC, Wh1isper commented
> Just as a side note, you should create a branch on your fork before making a PR, instead of committing on `main`.

Thanks for the reminder, I realized that each PR will be squeezed into a new commit rather than just merged

2022-11-18 09:59 UTC, davidbrochart commented
In this particular case, I squashed your PR.