kernelspec related convert os.path into pathlib.Path as possiable.
jupyter-server/jupyverse pull request #256
Opened 2022-12-14 04:09 UTC by specter119

2022-12-14 08:32 UTC, davidbrochart requested changes
Thanks @specter119.
I would also suggest opening a PR in jupyter-core and change [this file](https://github.com/jupyter/jupyter_core/blob/bc81ed6c8d80d4d360af2a857d802bbaa94087b4/jupyter_core/paths.py).

2022-12-14 08:32 UTC, davidbrochart commented on plugins/kernels/fps_kernels/kernel_driver/kernelspec.py
> +        SYSTEM_JUPYTER_PATH.append(Path(programdata) / "jupyter")
Why did you remove the `else`?

2022-12-14 08:32 UTC, davidbrochart commented on plugins/kernels/fps_kernels/kernel_driver/kernelspec.py
> +        paths.append(Path(os.environ["JUPYTER_PATH"]))
This is wrong because `JUPYTER_PATH` is a list of paths.

2022-12-14 08:32 UTC, davidbrochart commented on plugins/kernels/fps_kernels/kernel_driver/kernelspec.py
> +    paths = [p for p in paths if p.is_dir()]
Why not doing this check just before returning `paths`?

2022-12-14 08:32 UTC, davidbrochart commented on plugins/kernels/fps_kernels/kernel_driver/kernelspec.py
> +#     return path.is_dir() and (path / "kernel.json").is_file()
```suggestion
```

2022-12-14 08:32 UTC, davidbrochart commented on plugins/kernels/fps_kernels/kernel_driver/paths.py
> +# import uuid
```suggestion
```

2022-12-14 08:32 UTC, davidbrochart commented on plugins/kernels/fps_kernels/kernel_driver/paths.py
> +    return Path(os.path.expandvars(s))
This doesn't seem to keep the previous behavior.

2022-12-14 08:32 UTC, davidbrochart commented on plugins/kernels/fps_kernels/kernel_driver/paths.py
> +        #     path = os.getcwd()
Why commenting out?

2022-12-14 08:32 UTC, davidbrochart commented on plugins/kernels/fps_kernels/kernel_driver/paths.py
> +        xdg = Path(os.environ.get("XDG_DATA_HOME", "~/.local/share"))
Why not use `Path.home() / ".local" / "share"`?

2022-12-14 08:32 UTC, davidbrochart commented on plugins/kernels/fps_kernels/kernel_driver/paths.py
> +    # matches = [os.path.abspath(m) for m in matches]
The previous behavior is broken is you don't create absolute paths.

2022-12-15 00:31 UTC, specter119 commented
@davidbrochart It seems this PR changes the previous behavior, and I will close this and prepare a new one.

2022-12-15 00:31 UTC, closed without merging