Fix multiple sessions in one kernel bug
jupyter-server/jupyverse pull request #451
Opened 2024-12-11 12:09 UTC by rakhmaevao

I found the following error

### How to reproduce the bug?

1. Run jupyverse jupyterlab
2. Create a session for the kernel. The kernel itself will start and a session will be created for it.
3. Add another session to the running kernel.

#### Expected behavior

The session will be added

####  Actual behavior

Error (see below).

https://github.com/user-attachments/assets/a47f360f-531f-4122-8edf-e0cdde1a8052

```
  File "/home/rakhmaevao/Projects/jupyverse/plugins/kernels/fps_kernels/routes.py", line 187, in create_session
    connection_file=self.kernel_id_to_connection_file[kernel_id],
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: '68527f9d-7362-4c0a-ac66-d9e429a78246'
```

### How did I fix it?

1. After creating a new kernel (see step 2 of the instructions for reproducing the bug), I added the path to CONNFILE to the mapping. This allowed me to find the path to this file when starting a new session.
2. Additionally, I fixed the kernel restart when another session is created for it. The problem was that when creating an additional session, the KS was rewritten without kernelspec_path. I deleted this rewriting.

#### Confirmation of functionality

https://github.com/user-attachments/assets/bdcd4495-044a-45fd-8f1c-aac400454ef7

2024-12-11 13:09 UTC, rakhmaevao commented
It seems the tests are already broken. Will we be able to merge my PR or do I need to fix the tests?

@davidbrochart

2024-12-12 10:37 UTC, davidbrochart commented
Thanks @rakhmaevao, I'll look at this in the coming days.

2025-01-10 10:06 UTC, rakhmaevao commented
@davidbrochart any progress?

2025-01-17 15:00 UTC, davidbrochart requested changes

2025-01-17 15:00 UTC, davidbrochart commented on plugins/kernels/fps_kernels/routes.py
> -            kernels[kernel_id]["server"] = kernel_server
If it's an external kernel, you want to create the kernel server.

2025-01-22 05:02 UTC, rakhmaevao commented on plugins/kernels/fps_kernels/routes.py
> -            kernels[kernel_id]["server"] = kernel_server
I created it in line 186. Or did I misunderstand you?

2025-01-22 07:55 UTC, davidbrochart commented on plugins/kernels/fps_kernels/routes.py
> -            kernels[kernel_id]["server"] = kernel_server
It's created but not registered in `kernels`?

2025-01-22 10:23 UTC, rakhmaevao commented on plugins/kernels/fps_kernels/routes.py
> -            kernels[kernel_id]["server"] = kernel_server
I think I got you.

You're asking why I removed the server with the kernel cache.

I did this because otherwise an error occurs when rebooting the kernel if we have several sessions in the running kernel.

2025-02-04 14:05 UTC, rakhmaevao commented on plugins/kernels/fps_kernels/routes.py
> -            kernels[kernel_id]["server"] = kernel_server
@davidbrochart any progress?

2025-02-04 14:49 UTC, davidbrochart commented on plugins/kernels/fps_kernels/routes.py
> -            kernels[kernel_id]["server"] = kernel_server
I think your PR breaks the "external kernel" use case.

2025-02-27 16:55 UTC, closed without merging